package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Chronicle</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--red:#c44040;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:900px;margin:0 auto;padding:1rem}.overview{display:flex;gap:1.5rem;margin-bottom:1rem;font-size:.7rem;color:var(--leather)}.overview .stat b{display:block;font-size:1.2rem;color:var(--cream)}.toolbar{display:flex;gap:.5rem;margin-bottom:.8rem;flex-wrap:wrap;align-items:center}.toolbar select,.toolbar input{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.3rem .5rem;font-family:var(--mono);font-size:.72rem;outline:none}.toolbar input{flex:1;min-width:120px}.evt-row{display:flex;align-items:center;gap:.5rem;padding:.3rem .5rem;border-bottom:1px solid var(--bg3);font-size:.72rem}.evt-type{color:var(--gold);width:80px;flex-shrink:0;font-weight:600}.evt-source{color:var(--leather);width:60px;flex-shrink:0}.evt-subject{flex:1;color:var(--cd)}.sev{font-size:.55rem;padding:.05rem .25rem;border-radius:2px}.sev-info{color:var(--cm)}.sev-warning{color:var(--gold)}.sev-error{color:var(--red)}.sev-critical{color:var(--red);font-weight:700}.evt-time{color:var(--cm);font-size:.6rem;width:50px;flex-shrink:0}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Chronicle</span></h1><span style="font-size:.65rem;color:var(--cm)">POST /api/events</span></div>
<div class="main"><div class="overview" id="ov"></div>
<div class="toolbar"><select id="fType" onchange="load()"><option value="">All types</option></select><select id="fSource" onchange="load()"><option value="">All sources</option></select><input type="text" id="fSearch" placeholder="Search..." onkeydown="if(event.key==='Enter')load()"><button class="btn btn-p" onclick="load()">Filter</button></div>
<div id="list"></div></div>
<script>
async function api(u){return(await fetch(u)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function timeAgo(d){if(!d)return'';const s=Math.floor((Date.now()-new Date(d))/1e3);if(s<60)return s+'s';if(s<3600)return Math.floor(s/60)+'m';return Math.floor(s/3600)+'h'}
async function init(){const[sd,td,srd]=await Promise.all([api('/api/stats'),api('/api/types'),api('/api/sources')]);
document.getElementById('ov').innerHTML='<div class="stat"><b>'+sd.today+'</b>Today</div><div class="stat"><b>'+sd.total+'</b>Total</div><div class="stat"><b>'+sd.types+'</b>Types</div><div class="stat"><b>'+sd.sources+'</b>Sources</div>';
document.getElementById('fType').innerHTML='<option value="">All types</option>'+((td.types||[]).map(t=>'<option>'+esc(t.type)+'</option>').join(''));
document.getElementById('fSource').innerHTML='<option value="">All sources</option>'+((srd.sources||[]).map(s=>'<option>'+esc(s)+'</option>').join(''));load()}
async function load(){const p=new URLSearchParams();const t=document.getElementById('fType').value;if(t)p.set('type',t);const s=document.getElementById('fSource').value;if(s)p.set('source',s);const q=document.getElementById('fSearch').value;if(q)p.set('search',q)
const d=await api('/api/events?'+p);const events=d.events||[];
document.getElementById('list').innerHTML=events.length?events.map(e=>'<div class="evt-row"><span class="evt-type">'+esc(e.type)+'</span><span class="evt-source">'+esc(e.source)+'</span><span class="sev sev-'+e.severity+'">'+e.severity+'</span><span class="evt-subject">'+esc(e.subject||e.data?.substring(0,80))+'</span><span class="evt-time">'+timeAgo(e.created_at)+'</span></div>').join(''):'<div class="empty">No events yet. POST /api/events to start logging.</div>'}
init();setInterval(load,5000)
</script></body></html>`
